node1:
  build: /vagrant/docker/nodes
  restart: always

node2:
  build: /vagrant/docker/nodes
  restart: always

haproxy:
  build: /vagrant/docker/haproxy
  restart: always
  links:
      - node1
      - node2
  expose:
    - "80"
    - "443"
  ports:
    - "80:80"
    - "443:443"
